version: '3.9'

services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  canadian-swimming-rankings-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - name=value
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8000
    volumes:
      - ./mount/src:/app/src
